version: 2
updates:
  - package-ecosystem: "pip"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-type: "security"

  - package-ecosystem: "pip"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "security"
